version: '3.8'

services:
  # app:
  #   build: .
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - POSTGRES_HOST=postgres
  #     - POSTGRES_PORT=5555
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DATABASE=crypto_manager
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules

  postgres:
    image: postgres:15
    command: -p 5555
    ports:
      - "5555:5555"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=crypto_manager
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: