export enum ConfigEnum {
  MARKET_QUOTES_API_KEY = 'MARKET_QUOTES_API_KEY',
  MARKET_QUOTES_URI = 'MARKET_QUOTES_URI',
  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRATION_TIME = 'JWT_EXPIRATION_TIME',
  BINANCE_API_KEY = 'BINANCE_API_KEY',
  BINANCE_API_SECRET = 'BINANCE_API_SECRET',
  AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID',
  AWS_SECRET_ACCESS_KEY = 'AWS_SECRET_ACCESS_KEY',
  AWS_REGION = 'AWS_REGION',
  AWS_S3_BUCKET_NAME = 'AWS_S3_BUCKET_NAME',
}
